### ISSUE TITLE
createStripeToken always return null/undefined.

### ISSUE THREAD

**Issue by chaitanyapilaka** [plaid/plaid-node#124]
Hey! 

I've been trying to use the createStripeToken method but even with all the right credentials and tokens, it seems to be returning null/undefined. I tried manually requesting the stripe token using post man with the same credentials/sandbox accounts and it returned a valid token. Any help would be appreciated!

**Comment by bethqiang** [comment]
@chaitanyapilaka did you ever figure this out? I'm currently experiencing this problem - createStripeToken is always returning `undefined` for me. 😢

**Comment by bethqiang** [comment]
So, even though the docs say that `createStripeToken` can be used in a promise, I had to promisify it myself in order for it to return anything other than `undefined--

```
function promisifiedCreateStripeToken(accessToken, plaidAccountId) {
  return new Promise(function(resolve, reject) {
    plaidClient.createStripeToken(accessToken, plaidAccountId, function(err, res) {
      if (err) return reject(err);
      resolve(res);
    });
  });
}
```

With that, I get the expected response.

**Comment by jondkoon** [comment]
ran into this today as well

**Comment by chaitanyapilaka** [comment]
I ended up manually sending a request to the plaid endpoint instead of using the library for this. Seems like a simple enough fix.

**Comment by michaelckelly** [comment]
@chaitanyapilaka @jondkoon @bethqiang - #129 should fix this, I will publish a new version once it is merged. Thanks for the patience!

**Comment by michaelckelly** [comment]
`plaid@2.0.5` has just been published with this fix

**Comment by hotcakedev628** [comment]
I am still facing this issue.
What is the solution?
My node version is 12.13.0 and plaid version is 8.1.2.

**Comment by hotcakedev628** [comment]
Hey, @michaelckelly , @chaitanyapilaka , @bethqiang 

Here's my code.

```
const exchangeLinkToken = async (linkToken, accountId) => {
  try {
    const tokenResponse = await client.exchangePublicToken(linkToken);
    const accessToken = tokenResponse.access_token;
    const bankAccountToken = await client.createStripeToken(accessToken, accountId);
    console.log('stripe token response', bankAccountToken)
    // It is undefined and says { <Pending> }
    return bankAccountToken;
  } catch (error) {
    throw error
  }
}
```
